
FROM node:14 as build

WORKDIR /app

EXPOSE 3000

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "start" ]

# RUN npm run build

# FROM nginx:latest

# COPY --from=build /app/build /usr/share/nginx/html

# CMD ["nginx", "-g", "daemon off;"]
